export interface GameItem {
    name: string
    logo: string
}

export const gameList: GameItem[] = [
    { name: "PG", logo: "/assets/Images/product/pg2.png" },
    { name: "JL", logo: "/assets/Images/product/jili.png" },
    { name: "TP", logo: "/assets/Images/product/tp.png" },
    { name: "Play", logo: "/assets/Images/product/pp.png" },
    { name: "CQ9", logo: "/assets/Images/product/cq9.png" },
    { name: "M", logo: "/assets/Images/product/mg.png" },
    { name: "JDB", logo: "/assets/Images/product/jdb.png" },
    { name: "Spribe", logo: "/assets/Images/product/spribe.png" },
    { name: "FC", logo: "/assets/Images/product/fc.png" },
    { name: "VA", logo: "/assets/Images/product/va.png" },
    { name: "b", logo: "/assets/Images/product/bng.png" },
    { name: "KA", logo: "/assets/Images/product/ka.png" },
    { name: "Playstar", logo: "/assets/Images/product/ps.png" },
    { name: "Rich88", logo: "/assets/Images/product/r88.png" },
    { name: "Playtech", logo: "/assets/Images/product/pt.png" },
    { name: "FunTa", logo: "/assets/Images/product/ftg.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/mw.png" },
    { name: "FunTa", logo: "/assets/Images/product/yb.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/rtg.png" },
    { name: "FunTa", logo: "/assets/Images/product/.png" },
    { name: "FunTa", logo: "/assets/Images/product/.png" },
    { name: "FunTa", logo: "/assets/Images/product/jili.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/tp.png" },
    { name: "FunTa", logo: "/assets/Images/product/jdb.png" },
    { name: "FunTa", logo: "/assets/Images/product/ka.png" },
    { name: "FunTa", logo: "/assets/Images/product/fc.png" },
    { name: "FunTa", logo: "/assets/Images/product/ps.png" },
    { name: "FunTa", logo: "/assets/Images/product/mg.png" },
    { name: "FunTa", logo: "/assets/Images/product/r88.png" },
    { name: "FunTa", logo: "/assets/Images/product/ftg.png" },
    { name: "FunTa", logo: "/assets/Images/product/va.png" },
    { name: "FunTa", logo: "/assets/Images/product/rtg.png" },
    { name: "FunTa", logo: "/assets/Images/product/yb.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/ne.png" },
    { name: "FunTa", logo: "/assets/Images/product/cq9.png" },
]
